### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by ziadkiwan** [findxain/ChatOn#1]
Hello Findxain thank you for updating the version of androidim its so cool, i'm wondering what is the version of the php you are using ?

**Comment by ziadkiwan** [comment]
Hello FindXain, it seems that you are using version 5.6 because its working now, but the android-im.sql file is different in the messages table you have type and file that are not available in the android-im.sql you provided can you provide a copy of your table schema thank you!

**Comment by findxain** [comment]
@ziadkiwan check the new sql file i just reimport it.
